export const ACTION_TYPES = Object.freeze({
  FETCH_START: 'FETCH_START',
  FETCH_SUCCESS: 'FETCH_SUCCESS',
  FETCH_ERROR: 'FETCH_ERROR',
  UPDATE_JSONPLACEHOLDER_PRAM: 'UPDATE_JSONPLACEHOLDER_PRAM',
  UPDATE_PAGE_NUMBER: 'UPDATE_PAGE_NUMBER',
  INCREASE_PAGE_NUMBER: 'INCREASE_PAGE_NUMBER',
  ADD_TO_CART: 'ADD_TO_CART',
  REMOVE_FROM_CART: 'REMOVE_FROM_CART',
  UPDATE_PRODUCT_QTY: 'UPDATE_PRODUCT_QTY',
  UPDATE_SEARCH_PRAM: 'UPDATE_SEARCH_PRAM',
  UPDATE_RATING_PRAM: 'UPDATE_RATING_PRAM',
});
