export const ACTION_TYPES = Object.freeze({
  FETCH_START: 'FETCH_START',
  FETCH_SUCCESS: 'FETCH_SUCCESS',
  FETCH_ERROR: 'FETCH_ERROR',
  UPDATE_JSONPLACEHOLDER_PRAM: 'UPDATE_JSONPLACEHOLDER_PRAM',
  UPDATE_PAGE_NUMBER: 'UPDATE_PAGE_NUMBER',
});
